[package]
name = "unity_datasets"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "unity_datasets"  # 실행 파일 이름
path = "src/main.rs"  # 바이너리로 사용할 파일 경로
